{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import random\n",
    "import time\n",
    "import traceback\n",
    "\n",
    "# 1. write this for an api call that can return 200 or any other error code\n",
    "# 2. write this for an api call that returns an actual error\n",
    "\n",
    "class CodeCommitApiError(Exception):\n",
    "    def __init__(self):\n",
    "        print(f'Error: AWS CodeCommit server is likely down, try again in a short amount of time')\n",
    "\n",
    "class S3ApiError(Exception):\n",
    "    def __init__(self):\n",
    "        print(f'Error: AWS S3 server is likely down\\n')\n",
    "\n",
    "def retry(function_name, retry_count=3):\n",
    "        def retry_wrapper(*args, **kwargs):\n",
    "            counter = 0\n",
    "            while counter <= retry_count:\n",
    "                try:\n",
    "                    return function_name(*args, **kwargs)\n",
    "\n",
    "                except S3ApiError as error:\n",
    "                    counter += 1\n",
    "                    if counter <= retry_count:\n",
    "                        print(f\"Retrying {counter}/{retry_count}:\")\n",
    "                    else:\n",
    "                        print(f\"max amount of retries reached: {counter-1}/{retry_count}\")\n",
    "                        raise\n",
    "                    time.sleep(.75)\n",
    "                    \n",
    "                except Exception as error:\n",
    "                    print(traceback.format_exc())\n",
    "                    counter += 1\n",
    "                    if counter <= retry_count:\n",
    "                        print(f\"Retrying {counter}/{retry_count}:\")\n",
    "                    else:\n",
    "                        print(f\"max amount of retries reached: {counter-1}/{retry_count}\")\n",
    "                        raise CodeCommitApiError()\n",
    "                    time.sleep(.75)\n",
    "        return retry_wrapper\n",
    "\n",
    "\n",
    "class Deployer():\n",
    "    def __init__(self):\n",
    "        self.STEP_COUNT = 0\n",
    "        self.STEP_MAX = 2 \n",
    "\n",
    "    def next_step_log_message(self):\n",
    "            self.STEP_MAX = 2\n",
    "            self.STEP_COUNT += 1\n",
    "            print(f'\\n')\n",
    "            print(f'Step: {self.STEP_COUNT}/{self.STEP_MAX}')\n",
    "            print(f'____________________________')\n",
    "    \n",
    "    @retry\n",
    "    def codecommit_api_call(self, first_number, last_number):\n",
    "        \"\"\"case where api returns an actual error\"\"\"\n",
    "        print(f'attempting to divide the given numbers: {first_number}/{last_number}')\n",
    "        print(f'Answer to division: {first_number/last_number}')\n",
    "    \n",
    "    @retry\n",
    "    def s3_api_call(self, first_number, last_number):\n",
    "        \"\"\" case where api call can return 200 or anything else \"\"\"\n",
    "        # api_call_response = api.api_call(arg1, arg 2)\n",
    "        response_code = random.randint(first_number, last_number)\n",
    "        if response_code == 200:\n",
    "            print(f'Success: {response_code}')\n",
    "            return response_code\n",
    "        else:\n",
    "            print(f'Fail: {response_code}')\n",
    "            raise S3ApiError()\n",
    "    \n",
    "\n",
    "# now this is the \"high level function\", which is sitting in another file\n",
    "# ________________________________________________________________\n",
    "@retry\n",
    "def high_level_function():\n",
    "    print('high level function begining')\n",
    "    deployer = Deployer()\n",
    "    try:\n",
    "        deployer.next_step_log_message()\n",
    "        deployer.codecommit_api_call(5,1)\n",
    "        \n",
    "        deployer.next_step_log_message()\n",
    "        deployer.s3_api_call(400,550)\n",
    "        \n",
    "        print('\\n___________________________________________')\n",
    "        print('high level function completed successfully')\n",
    "    except CodeCommitApiError:\n",
    "        print('\\nHigh level function did not complete')\n",
    "        print('Retrying entire app flow')\n",
    "        raise\n",
    "    except S3ApiError:\n",
    "        print('AWS S3 server appears to be down')\n",
    "        print(f\"Try again in a short amount of time\")\n",
    "        print('\\nHigh level function did not complete')\n",
    "        print('Retrying entire app flow')\n",
    "        raise\n",
    "    except Exception:\n",
    "        print(traceback.format_exc())\n",
    "        print('\\nHigh level function did not complete')\n",
    "        print('Retrying entire app flow')\n",
    "    finally:\n",
    "        print('Cleaning up temporary files\\n\\n\\n')\n",
    "\n",
    "print('executing high level function')\n",
    "high_level_function()\n"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "81794d4967e6c3204c66dcd87b604927b115b27c00565d3d43f05ba2f3a2cb0d"
  },
  "kernelspec": {
   "display_name": "Python 3.9.7 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.9.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
